const D = [
  {t:"destacados",e:"jazz",a:"Keith Jarrett",d:"The Köln Concert",ed:"Japón · 2 LPs",g:"VG+ / VG",p:119000,w:"Un esencial. Piano solo improvisado, con un clima espiritual que conecta con Alice Coltrane."},
  {t:"destacados",e:"jazz",a:"Charlie Haden / Jan Garbarek / Egberto Gismonti",d:"Folk Songs",ed:"Japón · ECM",g:"VG / VG",p:75000,w:"Jazz, folk y Brasil. Hermoso, y el puente perfecto entre jazz y MPB."},
  {t:"destacados",e:"electrónica",a:"Yellow Magic Orchestra",d:"Public Pressure",ed:"Japón",g:"EX / VG+",p:89000,tags:["origen"],w:"Electrónica pionera japonesa en prensa de su país de origen. Va con el lado kraut."},
  {t:"destacados",e:"electrónica",a:"Penguin Cafe Orchestra",d:"Penguin Cafe Orchestra",ed:"Japón",g:"VG+ / VG",p:129000,w:"Música de cámara rara y minimalista, con algo de library music. Caro, pero muy de nosotros."},
  {t:"destacados",e:"prog",a:"Robert Fripp",d:"Exposure",ed:"USA",g:"VG+ / VG+",p:69900,w:"Fripp con Eno, Peter Hammill y Peter Gabriel. Experimental y filoso."},
  {t:"destacados",e:"prog",a:"U.K.",d:"U.K.",ed:"Japón",g:"VG+ / VG",p:99000,w:"Superbanda prog con Wetton, Bruford y Holdsworth. Para los que aman Starless and Bible Black."},
  {t:"destacados",e:"prog",a:"Yes",d:"Relayer",ed:"USA",g:"VG+ / VG+",p:33000,tags:["ganga"],w:"El Yes más jazzero y salvaje (The Gates of Delirium). La ganga de la lista."},
  {t:"destacados",e:"rock",a:"Lou Reed",d:"Berlin",ed:"Japón",g:"VG+ / VG",p:99900,w:"Oscuro y operístico. Obra maestra."},
  {t:"destacados",e:"punk / new wave",a:"Elvis Costello",d:"My Aim Is True",ed:"UK",g:"VG+ / VG",p:59000,w:"El debut. Si es UK de época, es original de origen."},
  {t:"destacados",e:"metal / hard rock",a:"Judas Priest",d:"Priest in the East",ed:"Japón",g:"VG+ / VG",p:79000,tags:["alerta:falta el single"],w:"Unleashed in the East con el título japonés. Le falta el single de regalo que traía."},
  {t:"destacados",e:"metal / hard rock",a:"Rainbow",d:"On Stage",ed:"Japón",g:"VG+ / VG+",p:99000,w:"Rainbow con Dio, en vivo en su mejor momento."},
  {t:"destacados",e:"soul / funk",a:"Material",d:"Memory Serves",ed:"Japón",g:"VG+ / VG+",p:99000,w:"Funk de vanguardia de Nueva York: Bill Laswell, Fred Frith, Sonny Sharrock. Muy raro."},
  {t:"destacados",e:"mpb",a:"Gal Costa",d:"Gal Tropical",ed:"Japón",g:"VG+ / VG",p:65000,w:"MPB en prensa japonesa. Curioso y lindo."},
  {t:"destacados",e:"mpb",a:"Milton Nascimento",d:"Paixão e Fé",ed:"Brasil",g:"EX / G",p:29000,tags:["origen","ganga"],w:"Prensa de origen. El disco está excelente y la tapa gastada: ideal para escuchar."},
  {t:"también",e:"jazz",a:"Keith Jarrett",d:"Invocations / The Moth and the Flame",ed:"Japón · ECM · 2 LPs",g:"EX / VG+",p:139000,w:"Órgano de tubos y piano solo. Muy espiritual."},
  {t:"también",e:"jazz",a:"Egberto Gismonti",d:"Solo",ed:"Japón · promo",g:"EX / G+",p:69000,w:"Guitarra y piano del brasileño en ECM. Tapa gastada."},
  {t:"también",e:"jazz",a:"Duke Ellington & Count Basie",d:"First Time! The Count Meets the Duke",ed:"Japón",g:"EX / VG+",p:95000,w:"Las dos big bands juntas. Clásico del swing."},
  {t:"también",e:"jazz",a:"John Coltrane",d:"Coltranology Vol. 1",ed:"Japón · promo",g:"VG+ / VG",p:124500,w:"Vivos de 1961. Caro."},
  {t:"también",e:"jazz",a:"John Coltrane",d:"Coltranology Vol. 2",ed:"Japón · promo",g:"VG+ / VG",p:124500,w:"Continuación del volumen 1. Caro."},
  {t:"también",e:"prog",a:"Genesis",d:"Selling England by the Pound",ed:"Japón · promo",g:"VG / VG+",p:149000,w:"De lo mejor del prog inglés. Caro."},
  {t:"también",e:"prog",a:"Genesis",d:"Foxtrot",ed:"Japón",g:"VG+ / G",p:99000,tags:["alerta:tapa G"],w:"Discazo (Supper's Ready), pero la tapa está en mal estado."},
  {t:"también",e:"prog",a:"Emerson, Lake & Palmer",d:"Tarkus",ed:"Japón",g:"VG+ / VG",p:79000,w:"La suite de ELP en su mejor momento."},
  {t:"también",e:"prog",a:"Steve Hackett",d:"Voyage of the Acolyte",ed:"Japón",g:"VG+ / VG",p:99000,w:"El primero solista de Hackett, con la base de Genesis."},
  {t:"también",e:"prog",a:"Jon Anderson",d:"Olias of Sunhillow",ed:"Japón",g:"EX / EX",p:99000,w:"Prog cósmico que tocó casi todo solo. Muy buen estado."},
  {t:"también",e:"prog",a:"Bill Bruford & Patrick Moraz",d:"Music for Piano and Drums",ed:"Japón",g:"EX / EX",p:99000,w:"Dúo de piano y batería, íntimo y jazzero."},
  {t:"también",e:"electrónica",a:"Jean-Michel Jarre",d:"Équinoxe",ed:"Japón",g:"sin dato",p:59000,w:"Electrónica clásica francesa. Preguntar el estado."},
  {t:"también",e:"electrónica",a:"Eberhard Schoener",d:"Video Magic",ed:"USA",g:"sin dato",p:69000,w:"Electrónica alemana con Sting y Andy Summers. Preguntar el estado."},
  {t:"también",e:"punk / new wave",a:"Sex Pistols",d:"The Great Rock 'n' Roll Swindle",ed:"Japón · 2 LPs",g:"EX / VG+",p:119000,w:"La banda de sonido del mito, en prensa japonesa."},
  {t:"también",e:"punk / new wave",a:"Soft Cell",d:"Non-Stop Erotic Cabaret",ed:"Japón",g:"sin dato",p:75000,w:"Clásico del synth-pop oscuro (Tainted Love). Preguntar el estado."},
  {t:"también",e:"punk / new wave",a:"XTC",d:"Mummer",ed:"Japón",g:"EX / EX",p:99000,w:"El XTC más pastoral. Muy buen estado."},
  {t:"también",e:"punk / new wave",a:"Japan",d:"Obscure Alternatives",ed:"Japón",g:"EX / VG+",p:69900,w:"La banda Japan prensada en Japón, donde eran enormes."},
  {t:"también",e:"punk / new wave",a:"The Boomtown Rats",d:"A Tonic for the Troops",ed:"sin país",g:"VG+ / VG+",p:39000,w:"Punk y new wave de Geldof (Rat Trap). Preguntar la edición."},
  {t:"también",e:"punk / new wave",a:"The Jam",d:"Dig the New Breed",ed:"Canadá",g:"EX / EX",p:55000,w:"El vivo de The Jam. Muy buen estado."},
  {t:"también",e:"metal / hard rock",a:"Deep Purple",d:"Burn",ed:"Japón",g:"sin dato",p:69000,w:"Coverdale y Hughes. Llevar esta copia, no la de $39.000 en G / G."},
  {t:"también",e:"metal / hard rock",a:"Led Zeppelin",d:"Led Zeppelin II",ed:"Japón",g:"VG+ / VG+",p:129000,w:"Esencial. Caro."},
  {t:"también",e:"metal / hard rock",a:"Jimi Hendrix",d:"Jimi Plays Monterey",ed:"Japón",g:"VG / VG+",p:99000,w:"El vivo histórico de Monterey 1967."},
  {t:"también",e:"metal / hard rock",a:"Queen",d:"Queen I",ed:"Japón",g:"sin dato",p:59900,w:"El debut, el Queen más pesado. Preguntar el estado."},
  {t:"también",e:"metal / hard rock",a:"Aerosmith",d:"Draw the Line",ed:"Japón",g:"VG+ / VG",p:65000,w:"Más flojo que Rocks, que ya estamos evaluando."},
  {t:"también",e:"cantautores",a:"Tom Waits",d:"Franks Wild Years",ed:"Japón",g:"EX / EX",p:149000,w:"Waits en su etapa más teatral. Caro."},
  {t:"también",e:"cantautores",a:"Bob Dylan",d:"John Wesley Harding",ed:"Japón",g:"EX / VG",p:59000,w:"Dylan seco y bíblico. Muy buen precio para una japonesa."},
  {t:"también",e:"cantautores",a:"Mercedes Sosa",d:"Hasta la Victoria · Mujeres Argentinas · Con Sabor a Mercedes Sosa",ed:"Japón",g:"VG+ / VG",p:69000,w:"Curiosidad: Mercedes prensada en Japón. $69.000 cada uno."},
  {t:"también",e:"flamenco",a:"Paco de Lucía",d:"Interpreta a Manuel de Falla",ed:"Japón",g:"EX / EX",p:59900,w:"Género nuevo para la colección. Muy buen estado."},
  {t:"evitar",e:"rock",a:"Talking Heads",d:"Fear of Muzak",ed:"Bootleg",g:"sin dato",p:69000,tags:["alerta:bootleg"],w:"Marcado BOOT en la lista: grabación no oficial."},
  {t:"evitar",e:"rock",a:"Boston",d:"The Band from the Platinum Basement",ed:"Bootleg",g:"VG+ / G+",p:85000,tags:["alerta:bootleg"],w:"Marcado BOOT en la lista: grabación no oficial."},
  {t:"evitar",e:"metal / hard rock",a:"Thin Lizzy",d:"Life Live",ed:"Corea",g:"VG / VG",p:129000,tags:["alerta:prensa floja"],w:"Las prensas coreanas de esa época suelen ser de baja calidad. Muy caro para lo que es."},
  {t:"evitar",e:"rock",a:"David Bowie",d:"Station to Station",ed:"Japón",g:"VG+ / VG",p:129000,w:"Ya elegimos la UK original de 1976 en Javierfan, en mejor estado y más barata."},
  {t:"evitar",e:"punk / new wave",a:"Ian Dury & The Blockheads",d:"Do It Yourself",ed:"Japón",g:"VG / G",p:59000,w:"Estado flojo. En Javierfan está la UK original impecable por $63.200."},
  {t:"evitar",e:"metal / hard rock",a:"Deep Purple",d:"Burn",ed:"Japón",g:"G / G",p:39000,tags:["alerta:G / G"],w:"Copia en mal estado. Mejor la otra de $69.000."},
];
